### ISSUE TITLE
Create "Mentor" model under "users" app

### ISSUE THREAD

**Issue by prakhar-asaiya** [TCP-Tech/mentorship-backend#18]
Refer [here](https://drive.google.com/file/d/1rjZe-7mgDX1MGz6FY9YgBMY7_IpSH26-/view?usp=share_link) document for "Mentor" model creation in users/models.py

Avoid using prefix of table name in the table fields. For eg. In the PDF if "mentor_name" is written then use it as "name" only.

Also generate the migrations for this app.

**Comment by virajchandra51** [comment]
please assign me this issue

**Comment by prakhar-asaiya** [comment]
Sure @virajchandra51.
