### ISSUE TITLE
Create "Question" model under "questions" app

### ISSUE THREAD

**Issue by prakhar-asaiya** [TCP-Tech/mentorship-backend#19]
Refer [here](https://drive.google.com/file/d/1rjZe-7mgDX1MGz6FY9YgBMY7_IpSH26-/view?usp=share_link) document for "Question" model creation in questions/models.py

Avoid using prefix of table name in the table fields. For eg. In the PDF if "question_name" is written then use it as "name" only.

Refer to DSA_Q table in pdf for the model.

Also generate the migrations for this app.

**Comment by animesh288** [comment]
Hey, can you assign me this issue

**Comment by animesh288** [comment]
Hey, can you assign me this issue

**Comment by prakhar-asaiya** [comment]
Sure @animesh288.
