### ISSUE TITLE
Add swagger docs support

### ISSUE THREAD

**Issue by sahil9001** [TCP-Tech/mentorship-backend#21]
**Problem**
It is great to have all API docs in one place. Especially if it is interactive and provides examples on response, request body etc.,

**Solution**
Integrate swagger docs into the django server with help of django-yasg package. Refer this [PR](https://github.com/ECellNitrr/teesco-backend/pull/53/files)

**Comment by animesh288** [comment]
Hey, I would like to work on this issue

**Comment by prakhar-asaiya** [comment]
Okay @animesh288.
