### ISSUE TITLE
Create "Topic" model under "questions" app

### ISSUE THREAD

**Issue by prakhar-asaiya** [TCP-Tech/mentorship-backend#22]
Create a model "Topic" in questions/models.py.

Required fields are : id and name.

Avoid using prefix of table name in the table fields.

Also generate the migrations for this app.

**Comment by sahil9001** [comment]
Hey please assign me this issue

**Comment by Kraniket901** [comment]
Hey, can you please assign me this issue

**Comment by prakhar-asaiya** [comment]
Sure @Kraniket901.
